name: train_random_forest
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - hydra-core=1.3.2
  - matplotlib=3.10.8
  - pandas=2.3.3
  - pip=26.0.1
  - scikit-learn=1.8.0
  - numpy=1.26.4
  - pip:
      - mlflow==3.10.0
      - wandb==0.25.0
